ogcio/shared-node-utils

- package-lock.json
- packages/fastify-error-handler/CHANGELOG.md
- packages/fastify-error-handler/package.json
- packages/fastify-logging-wrapper/CHANGELOG.md
- packages/fastify-logging-wrapper/package.json
> Fix: publish shared errors for version 5

- package-lock.json
- packages/fastify-logging-wrapper/package.json
> fix(fastify-logging-wrapper): installed shared errors

- packages/fastify-error-handler/CHANGELOG.md
- packages/fastify-error-handler/package.json
- packages/fastify-logging-wrapper/CHANGELOG.md
- packages/fastify-logging-wrapper/package.json
> chore(core): changelog

- package-lock.json
- packages/fastify-logging-wrapper/__tests__/fastify-logging-wrapper.errors.test.ts
- packages/fastify-logging-wrapper/__tests__/helpers/build-fastify.ts
- packages/fastify-logging-wrapper/src/fastify-logging-wrapper.ts
…no instance
added customConfig for initialize new pino or use default fastify instance
> feat(fastify-logging-wrapper): add customConfig for initialize new pino instance

- .vscode/settings.json
- biome.jsonc
- lerna.json
- package-lock.json
- package.json
- packages/fastify-error-handler/__tests__/helpers/build-fastify.ts
- packages/fastify-error-handler/__tests__/helpers/fastify-test-helpers.ts
- packages/fastify-error-handler/__tests__/initialize-error-handler.test.ts
- packages/fastify-error-handler/__tests__/life-events-error-handler.test.ts
- packages/fastify-error-handler/src/index.ts
- packages/fastify-error-handler/src/initialize-error-handler.ts
- packages/fastify-logging-wrapper/__tests__/fastify-logging-wrapper.errors.test.ts
- packages/fastify-logging-wrapper/__tests__/fastify-logging-wrapper.test.ts
- packages/fastify-logging-wrapper/__tests__/helpers/build-fastify.ts
- packages/fastify-logging-wrapper/__tests__/helpers/build-logger.ts
- packages/fastify-logging-wrapper/__tests__/helpers/fastify-test-helpers.ts
- packages/fastify-logging-wrapper/__tests__/logging-wrapper.test.ts
- packages/fastify-logging-wrapper/src/fastify-logging-wrapper.ts
- packages/fastify-logging-wrapper/src/index.ts
- packages/fastify-logging-wrapper/src/logging-wrapper-entities.ts
- packages/fastify-logging-wrapper/src/logging-wrapper.ts
> chore: added biome

- .vscode/settings.json
- biome.jsonc
- lerna.json
- package-lock.json
- package.json
- packages/fastify-error-handler/__tests__/helpers/build-fastify.ts
- packages/fastify-error-handler/__tests__/helpers/fastify-test-helpers.ts
- packages/fastify-error-handler/__tests__/initialize-error-handler.test.ts
- packages/fastify-error-handler/__tests__/life-events-error-handler.test.ts
- packages/fastify-error-handler/src/index.ts
- packages/fastify-error-handler/src/initialize-error-handler.ts
- packages/fastify-logging-wrapper/__tests__/fastify-logging-wrapper.errors.test.ts
- packages/fastify-logging-wrapper/__tests__/fastify-logging-wrapper.test.ts
- packages/fastify-logging-wrapper/__tests__/helpers/build-fastify.ts
- packages/fastify-logging-wrapper/__tests__/helpers/build-logger.ts
- packages/fastify-logging-wrapper/__tests__/helpers/fastify-test-helpers.ts
- packages/fastify-logging-wrapper/__tests__/logging-wrapper.test.ts
- packages/fastify-logging-wrapper/src/fastify-logging-wrapper.ts
- packages/fastify-logging-wrapper/src/index.ts
- packages/fastify-logging-wrapper/src/logging-wrapper-entities.ts
- packages/fastify-logging-wrapper/src/logging-wrapper.ts
- packages/shared-errors/tsconfig.json
> chore(): added Biome for linting

- package-lock.json
- package.json
> chore: updated deps for v4

- package-lock.json
- package.json
- packages/fastify-error-handler/package.json
- packages/fastify-logging-wrapper/package.json
> Chore: update deps to 5.1.0

- .gitignore
- package-lock.json
- package.json
- packages/fastify-error-handler/package.json
- packages/fastify-error-handler/vitest.config.mts
- packages/fastify-logging-wrapper/package.json
- packages/fastify-logging-wrapper/src/fastify-logging-wrapper.ts
- packages/fastify-logging-wrapper/vitest.config.mts
> chore: dependabot v5

- package-lock.json
- package.json
- packages/fastify-logging-wrapper/__tests__/logging-wrapper.test.ts
- packages/fastify-logging-wrapper/package.json
- packages/fastify-logging-wrapper/src/fastify-logging-wrapper.ts
- packages/fastify-logging-wrapper/src/logging-wrapper.ts
Add the possibility to set custom options when instantianting logger
- [] **Dev change**
> Chore(v4): add custom options to the logger

- package-lock.json
- package.json
- packages/api-auth/package.json
- packages/api-auth/src/logto-client/user-scope.ts
Use const instead of enum declaration
> Chore(v4) use const instead of enum

- .github/dependabot.yaml
- commitlint.config.js
- package-lock.json
- packages/nextjs-logging-wrapper/README.md
- packages/nextjs-logging-wrapper/package.json
- packages/nextjs-logging-wrapper/src/client-logger.ts
- packages/nextjs-logging-wrapper/src/common-logger.ts
- packages/nextjs-logging-wrapper/src/server-logger.ts
- packages/nextjs-logging-wrapper/src/shared.ts
- packages/nextjs-logging-wrapper/tsconfig.json
- packages/nextjs-logging-wrapper/tsconfig.prod.json
> Feat: nextjs logging wrapper

- package-lock.json
- packages/nextjs-logging-wrapper/package.json
Fixed exports for multiple modules
> fix(nextjs-logging-wrapper): fixed exports

- package-lock.json
- packages/nextjs-logging-wrapper/package.json
> fix: set version to 14.2.5

- .github/dependabot.yaml
- commitlint.config.js
- package-lock.json
- packages/api-auth/package.json
- packages/nextjs-auth/package.json
- packages/nextjs-auth/src/auth-session.ts
- packages/nextjs-auth/src/authentication-context.ts
- packages/nextjs-auth/src/base-authentication-context.ts
- packages/nextjs-auth/src/check-permissions.ts
- packages/nextjs-auth/src/index.ts
- packages/nextjs-auth/src/route.ts
- packages/nextjs-auth/src/sessions.ts
- packages/nextjs-auth/src/types.ts
- packages/nextjs-auth/tsconfig.json
- packages/nextjs-auth/tsconfig.prod.json
- packages/nextjs-logging-wrapper/package.json
> Feat: 23990 - nextjs auth added as package

- packages/life-events-ds/package.json
- packages/life-events-ds/tsconfig.json
> fix(): fix ds build

- package-lock.json
update lock with latest life-events-ds
> fix(): update lock with latest life-events-ds

- package-lock.json
- package.json
- packages/nextjs-analytics/package.json
- packages/nextjs-analytics/src/AnalyticsTracker.tsx
- packages/nextjs-analytics/src/useAnalyticsTracker.test.ts
Upgrade BB SDK for nextjs-analytics
> Chore(): Upgrade BB SDK for nextjs-analytics

- package-lock.json
- packages/nextjs-auth/package.json
Removed console log from nextjs auth
> chore(nextjs-auth): publish 3.5.1

- packages/nextjs-auth/src/authentication-context.ts
- packages/nextjs-auth/src/base-authentication-context.ts
Added clear contexts method
Not willing to deploy a new version for this. added for future use
> chore: added clear contexts method

- .vscode/settings.json
- package-lock.json
- packages/fastify-o11y-plugin/README.md
- packages/fastify-o11y-plugin/__test__/build-fastify.ts
- packages/fastify-o11y-plugin/__test__/fastify-o11y-plugin.error.test.ts
- packages/fastify-o11y-plugin/__test__/fastify-o11y-plugin.test.ts
- packages/fastify-o11y-plugin/package.json
- packages/fastify-o11y-plugin/src/index.ts
- packages/fastify-o11y-plugin/tsconfig.json
- packages/fastify-o11y-plugin/tsconfig.prod.json
- packages/fastify-o11y-plugin/vitest.config.mts
Observability plugin to include custom header with current `traceId`
Related to issue: [26188](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/26188/)
> feat: o11y shared plugin AB#26188

- package-lock.json
- packages/fastify-o11y-plugin/__test__/build-fastify.ts
- packages/fastify-o11y-plugin/__test__/fastify-o11y-plugin.test.ts
- packages/fastify-o11y-plugin/package.json
- packages/fastify-o11y-plugin/src/index.ts
Added access control request headers management 
Related to issue: [26188](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/26188/)
> feat: add access control headers to o11y plugin AB#26188

- package-lock.json
- packages/nextjs-auth/package.json
- packages/nextjs-auth/src/user-context-handler.ts
Use the selected org id as org id to get token
> Fix: get token with org id

- package-lock.json
- packages/nextjs-auth/package.json
- packages/nextjs-auth/src/types.ts
> fix: add domain param

- package-lock.json
- packages/nextjs-auth/package.json
- packages/nextjs-auth/src/types.ts
- packages/nextjs-auth/src/user-context-handler.ts
Ask for custom data and add orginal context to getUser
> Feat(nextjs-auth): add original context to get user

- package-lock.json
- packages/fastify-logging-wrapper/package.json
Related to Issue:
- [26429](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/26429/)
- [26766](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/26766)
> chore: bump patch release for fastify loggin wrapper AB#26429

- package-lock.json
- packages/fastify-logging-wrapper/__tests__/fastify-logging-wrapper.test.ts
- packages/fastify-logging-wrapper/package.json
- packages/fastify-logging-wrapper/src/fastify-logging-wrapper.ts
Backporting for fastify v4 of PR: [75](https://github.com/ogcio/shared-node-utils/pull/75)
> feat: skip internal objects serialize if empty - backport to v4 AB#26429

- packages/nextjs-auth/src/types.ts
- packages/nextjs-auth/src/user-context-handler.ts
- packages/nextjs-auth/src/utils/constants.ts
added isCitizenOnboarded() to auth utils
> AB#26562 - Simple citizen onboard check

- package-lock.json
- packages/nextjs-auth/package.json
> chore: bumped nextjs-auth version

- package-lock.json
- packages/nextjs-analytics/package.json
- packages/nextjs-analytics/src/index.ts
export client constructor class for `Analytics`
> chore: bump analytcs next version

- package-lock.json
- packages/nextjs-auth/package.json
> chore: bump nextjs-auth to `4.0.6`

- package-lock.json
- packages/nextjs-analytics/package.json
> chore: update analytics-sdk AB#28280

- package-lock.json
- packages/nextjs-analytics/package.json
> chore: bump nextjs-analytics to `0.2.1`

- packages/nextjs-analytics/README.md
- packages/nextjs-analytics/src/AnalyticsProvider.test.tsx
- packages/nextjs-analytics/src/AnalyticsProvider.tsx
- packages/nextjs-analytics/src/trackNavigationEvent.test.ts
Add documentation to nextjs-analytics package.
Also adds a couple extra tests and changes to async-await approach inside useEffect.
> docs: nextjs-analytics AB#28263

- package-lock.json
- packages/nextjs-auth/package.json
- packages/nextjs-auth/src/types.ts
- packages/nextjs-auth/src/user-context-handler.ts
Add get signin method to nextjs auth
> feat: add get signin method to nextjs auth

- package-lock.json
> chore: package lock update after nextjs-auth 5.0.3 release

- .github/dependabot.yaml
- .husky/pre-push
- commitlint.config.js
- package-lock.json
- packages/fastify-o11y/README.md
- packages/fastify-o11y/__test__/build-fastify.ts
- packages/fastify-o11y/__test__/fastify-o11y-plugin.error.test.ts
- packages/fastify-o11y/__test__/fastify-o11y-plugin.test.ts
- packages/fastify-o11y/package.json
- packages/fastify-o11y/src/index.ts
- packages/fastify-o11y/tsconfig.json
- packages/fastify-o11y/tsconfig.prod.json
- packages/fastify-o11y/vitest.config.mts
Adds fastify v4 compatible o11y plugin
> feat: v4 fastify o11y AB#29442

- package-lock.json
- packages/fastify-o11y/README.md
- packages/fastify-o11y/__test__/build-fastify.ts
- packages/fastify-o11y/__test__/fastify-o11y-plugin.error.test.ts
- packages/fastify-o11y/__test__/fastify-o11y-plugin.test.ts
- packages/fastify-o11y/package.json
- packages/fastify-o11y/src/index.ts
- packages/fastify-o11y/vitest.config.mts
Added onError hook to fastify-o11y for adding errors to traces|
[AB#29442](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_boards/board/t/Bismuth/Stories?System.IterationPath=%40currentIteration&workitem=29442)
> feat(fastify-o11y): error tracing AB#29442

- package-lock.json
- packages/fastify-o11y/package.json
> chore: bump fastify-o11y to 4.0.1 for v4
